---
apiVersion: v1
kind: Namespace
metadata:
  name: artha
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: artha-config
  namespace: artha
data:
  DATABASE_URL: "postgresql://postgres:postgres@postgres.artha.svc.cluster.local:5432/artha"
  SERVICE_PORT: "8001"
  PIPELINE_PORT: "8000"
  PORT: "3000"
